# Generated by Django 3.2.9 on 2021-11-11 05:42

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='main_app_details',
            fields=[
                ('name', models.CharField(default='Smart Tech', max_length=60, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(default='[Original size] Smart Tech(1).png', upload_to=accounts.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('profile_Pic', models.ImageField(default='undraw_profile.svg', upload_to=accounts.models.path_and_rename, verbose_name='Profile Picture')),
                ('user_type', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent'), ('blogger', 'blogger'), ('developer', 'developer'), ('designer', 'designer'), ('analyst', 'analyst')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_status', models.BooleanField(default=True)),
                ('site_number', models.PositiveSmallIntegerField(blank=True, default=254202346703, null=True)),
                ('email', models.URLField(blank=True, default='smarttech.allservices@gmail.com', null=True)),
                ('sms', models.PositiveSmallIntegerField(blank=True, default=254202346703, null=True)),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/c/254202346703', null=True)),
                ('facebook_page', models.URLField(blank=True, default='https://fb.me/smarttech.all', null=True)),
                ('facebook_direct_message', models.URLField(blank=True, default='https://m.me/smarttech.all', null=True)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/Jeff18309725', null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/smarttech.allservices', null=True)),
                ('youtube', models.URLField(blank=True, default='https://www.youtube.com/channel/UC4_F7e77uT7dG1EP99IdQow?sub_confirmation=1', null=True)),
                ('location', models.URLField(blank=True, default='https://goo.gl/maps/jXQMRKzCB8h2hQcf6', null=True)),
                ('site_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.main_app_details')),
            ],
        ),
    ]
