# Generated by Django 3.2.9 on 2021-11-11 18:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211111_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_app_details',
            name='logo',
            field=models.ImageField(default='[Original size] Smart Tech(1).png', upload_to=accounts.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='email',
            field=models.EmailField(blank=True, default='smarttech.allservices@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='facebook_page',
            field=models.CharField(blank=True, default='https://fb.me/smarttech.all', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='whatsapp',
            field=models.CharField(blank=True, default='https://wa.me/c/254202346703', max_length=300, null=True),
        ),
    ]
