# Generated by Django 3.2.9 on 2021-11-11 19:15

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211111_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_app_details',
            name='logo',
            field=models.ImageField(default='[Original size] Smart Tech(1).png', upload_to=accounts.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='facebook_page',
            field=models.URLField(blank=True, default='https://fb.me/smarttech.all', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='site_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.main_app_details'),
        ),
        migrations.AlterField(
            model_name='site_contacts',
            name='whatsapp',
            field=models.URLField(blank=True, default='https://wa.me/c/254202346703', max_length=300, null=True),
        ),
    ]
