# Generated by Django 3.2.9 on 2021-11-13 20:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211111_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AlterField(
            model_name='main_app_details',
            name='logo',
            field=models.ImageField(default='[Original size] Smart Tech(1).png', upload_to=accounts.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
