# Generated by Django 3.2.9 on 2021-12-15 15:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211211_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_app_details',
            name='logo',
            field=models.ImageField(default='[Original size] Smart Tech(1).png', upload_to=accounts.models.path_and_rename),
        ),
    ]
