# Generated by Django 3.2.9 on 2021-12-17 19:39

from django.db import migrations
import eschool.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=eschool.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=eschool.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
