# Generated by Django 3.2.9 on 2021-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='ecomerce/team/')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=200)),
                ('fb_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
