# Generated by Django 3.2.9 on 2021-12-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
