# Generated by Django 3.2.9 on 2021-12-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_alter_team_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='ecomerce/products/%Y/%m/%d'),
        ),
    ]
